<?php require 'templates/layout/header.phtml' ?>
       
          
        <h1><?= $jugador->nombre?></h1>

        <p>equipo: <?=$jugador->id_equipos?></p>
        <p>pais: <?=$jugador->pais ?></p>
        <p>pierna buena: <?=$jugador->pierna_buena?></p>
        <p>posicion <?=$jugador->posicion?></p>
        <p>fecha de nacimiento: <?=$jugador->fecha_nacimiento?></p>
        <p>altura: <?=$jugador->altura?></p>

<?php require 'templates/layout/footer.phtml' ?>