<?php require 'templates/layout/header.phtml' ?>
       
          
        <h1><?= $this->nombre?></h1>

        <p>equipo: <?=$this->id_equipos?></p>
        <p>pais: <?=$this->pais ?></p>
        <p>pierna buena: <?=$this->pierna_buena?></p>
        <p>posicion <?=$this->posicion?></p>
        <p>fecha de nacimiento: <?=$this->fecha_nacimiento?></p>
        <p>altura: <?=$this->altura?></p>

<?php require 'templates/layout/footer.phtml' ?>