<?php require 'templates/layout/header.phtml'; ?>
       
                  

        <h1><?= $jugador[0]-> nombre_j ?></h1>

        <p>equipo: <?=$jugador[0]->nombre_e;?></p>
        <p>pais: <?=$jugador[0]->pais_j; ?></p>
        <p>pierna buena: <?=$jugador[0]->pierna_buena?></p>
        <p>posicion <?=$jugador[0]->posicion?></p>
        <p>fecha de nacimiento: <?=$jugador[0]->fecha_nacimiento?></p>
        <p>altura: <?=$jugador[0]->altura?>cm</p>

<?php require 'templates/layout/footer.phtml'; ?>