 <?php
    require 'templates/layout/header.phtml' ?>
    <form action="updateTeam/<?php echo($equipo->id)?>" method="POST">

        <div class="row">
            <div class="col-9">
                <div class="form-group">
                    <label>nombre</label>
                    <input required name="nombre" type="text" class="form-control" value="<?php echo($equipo->nombre)?>"> 
                </div>
            </div>
            <div class="form-group">
            <label>Pais</label>
            <input name="pais" type="text" value="<?php echo($equipo->pais)?>">
            </div>
            <div class="form-group">
            <label>Ciudad</label>
            <input name="ciudad" type="text" value="<?php echo($equipo->ciudad)?>">
            </div>
            <div>
            <label>Año de fundacion</label>
            <input required name="fundacion" type="text" value="<?php echo($equipo->fundacion)?>" >
            </div>
        </div>


        <button type="submit" class="btn btn-primary mt-2">Modificar</button>

    </form>

    <?php require 'templates/layout/footer.phtml' ?>