
<?php require 'templates/layout/header.phtml' ?>

<form action="editar/<?php echo($player[0]->id)?>" method="POST">
     <div class="row">
        <div class="col-9">
            <div class="form-group">
                <label>nombre</label>
                <input required name="nombre" type="text" class="form-control" value=" <?php echo($player[0]->nombre_j)?>">
            </div>
        </div>
        <div class="form-group">
         <label>Equipo</label>
        <select class="form-select form-select-sm" aria-label="Small select example" required name="equipo"? value=" <?php echo($player[0]->id_equipos)?>">
          <?php foreach ($equipos as $equipo){ ?>
                 <option value=" <?php echo ($equipo->id) ?>"><?php echo($equipo->nombre) ?></option>
              <?php
            } ?>
        </select>
        </div>
        <div class="form-group">
         <label>Pierna Buena:</label>
           <select class="form-select form-select-sm" aria-label="Small select example" required name="pieBueno"value="<?php echo($player[0]->pierna_buena)?>">
            <option value="izq">izquierdo</option>
            <option value="der">derecho</option>
            <option value="amb">ambidiestro</option>
        </select>
        </div>
        <div>
        <label>Pais</label>
        <input required name="pais" type="text" value="<?php echo($player[0]->pais_j)?>" >
        </div>
        <div class="form-group">
        </select>

             <label>Posicion:</label>
           <select class="form-select form-select-sm" aria-label="Small select example" required name="posicion"value=" <?php echo($player[0]->posicion)?>">
            <option value="DF">Defensor</option>
            <option value="LT">Lateral</option>
            <option value="EXD">extremo derecho</option>
            <option value="EXI">Extremo izquierdo</option>
            <option value="DC">Delantero</option>
            <option value="MC">Mediocampista</option>
            <option value="PO">Portero</option>
        </select>
        </div>
        <div>
         <label>Fecha De Nacimiento</label>
        <input type="date" name="nacimiento" value="<?php echo($player[0]->fecha_nacimiento)?>">
        </div>
        <div class="form-group">
         <label>Altura(cm)</label>
         <input type="number" required name="altura" value=" <?php echo($player[0]->altura)?>">
         </div>





 <button type="submit" class="btn btn-primary mt-2">Modificar</button>

</form>

<?php require 'templates/layout/footer.phtml' ?>