<?php require 'templates/layout/header.phtml' ?>

    <form action="nuevo" method="POST">

     <div class="row">
        <div class="col-9">
            <div class="form-group">
                <label>nombre</label>
                <input required name="nombre" type="text" class="form-control">
            </div>
        </div>
        <div class="form-group">
         <label>Equipo</label>
        <select class="form-select form-select-sm" aria-label="Small select example" required name="equipo">
            <?php foreach ($equipos as $equipo){ ?>
                 <option value=" <?php echo ($equipo->id) ?>"><?php echo($equipo->nombre) ?></option>
              <?php
            } ?>
           
        </select>
        </div>
        <div class="form-group">
         <label>Pierna Buena:</label>
           <select class="form-select form-select-sm" aria-label="Small select example" required name="pieBueno">
            <option value="izq">izquierdo</option>
            <option value="der">derecho</option>
            <option value="amb">ambidiestro</option>
        </select>
        </div>
        <div>
        <label>Pais</label>
        <input required name="pais" type="text" >
        </div>
        <div class="form-group">
        </select>

             <label>Posicion:</label>
           <select class="form-select form-select-sm" aria-label="Small select example" required name="posicion">
            <option value="DF">Defensor</option>
            <option value="LT">Lateral</option>
            <option value="EXD">extremo derecho</option>
            <option value="EXI">Extremo izquierdo</option>
            <option value="DC">Delantero</option>
            <option value="MC">Mediocampista</option>
            <option value="PO">Portero</option>
        </select>
        </div>
        <div>
         <label>Fecha De Nacimiento</label>
        <input type="date" name="nacimiento">
        </div>
        <div class="form-group">
         <label>Altura(cm)</label>
         <input type="number" required name="altura">
         </div>






 <button type="submit" class="btn btn-primary mt-2">Agregar</button>

</form>

<?php require 'templates/layout/footer.phtml' ?>


