<?php require 'templates/layout/header.phtml' ?>


        <ul >
            <?php foreach($players as $player) { ?>
                <li>  <a href="jugador/<?= $player->id ?>" > <?= $player->nombre ?></a>
                        <p> <?= $player->id_equipos ?></p> 
                </li>
            <?php } ?>
        </ul>
                <button>agregar jugador</button>
                <button>eliminar jugador</button>
                <button>editar items</button>
        <p class="mt-3"><small>Mostrando <?=$count?> futbolistas</small></p>
  

<?php require 'templates/layout/footer.phtml' ?>