<?php require 'templates/layout/header.phtml' ?>


        <ul class="list-group list-group-numbered">
            <?php foreach($players as $player) { ?>
                <li class="list-group-item d-flex justify-content-between align-items-start"> <div class="ms-2 me-auto">
                       <div> <a href="jugador/<?= $player->id ?>" > <?= $player->nombre ?></a></div>
                        <div> <?= $player->id_equipos ?> </div>
                        <?php if($user):?>
                         <a class="btn btn-sm btn-outline-danger " href="eliminar/<?= $player->id ?>">Eliminar</a>
                          <a class="btn btn-outline-warning" href="cambiar/<?= $player->id ?>">Editar</a>
                          <?php endif?>
                         </div> 

                </li>
            <?php } ?>
        </ul>
               <?php if($user):?> <a href="agregar">Agregar Jugador</a><?php endif?>
   
  

<?php require 'templates/layout/footer.phtml' ?>