<?php require 'templates/layout/header.phtml' ?>


        <ul >
            <?php foreach($players as $player) { ?>
                <li>  <b> <?= $player->nombre ?></b>
                        <p> <?= $player->id_equipos ?></p> 
                </li>
            <?php } ?>
        </ul>

        <p class="mt-3"><small>Mostrando <?=$count?> futbolistas</small></p>
  

<?php require 'templates/layout/footer.phtml' ?>