{include 'templates/header.phtml'}
    <form>
        <div class="form-group">
            <label for="user">Usuario</label>
            <input type="username" class="form-control" id="email" placeholder="Enter email">
        </div>
        <div class="form-group">
            <label for="password">Contraseña</label>
            <input type="password" class="form-control" id="password" placeholder="Enter Password">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{include 'templates/footer.phtml'}
